blog/urls.py
from django.urls import path
from .views import *
from .admin import blog_admin

urlpatterns = [
    path('admin/', blog_admin.urls),
    path('', PostListView.as_view(), name='post-index'),
    path('create/', create_post, name='post-create'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('create-comment/<int:pk>/', create_comment, name='create-comment'),
    path('search/', search, name='search'),
    path('signup/',signup, name='signup'),
    path('signin/',signin, name='signin'),
    path('signout/',signout, name='signout'),
    path('edit-profile/',edit_profile, name='edit-profile'),
    path('like/<int:pk>/',like, name='like'),
    path('liked-posts/',liked_posts, name='liked-posts'),
    path('own-posts/',UserPostsView.as_view(), name='own-posts'),
    path('<str:category>/', CategoryView.as_view(), name='category-view'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from portfolio.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name="portfolio-index"),
    path('portfolio/', include('portfolio.urls')),
    path('blog/',include('blog.urls')),
    path('shop/',include('ecommerce.urls')),
    path('user/',include('user.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Post
from ckeditor.widgets import CKEditorWidget


category=[("wordpress","Wordpress"),("html","HTML"),
        ("photography","Photography"),("ui","UI"),
        ("mockups","Mockups"),("branding","Branding")]

class CraetePostForm(forms.Form):
    title=forms.CharField()
    category=forms.ChoiceField(choices=category)
    content=forms.CharField(widget=CKEditorWidget())
    image=forms.ImageField()


    title.widget.attrs.update({'class': 'full-width'})
    category.widget.attrs.update({'class': 'full-width'})
    
        
        

templates/components.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  <link rel="apple-touch-icon" sizes="180x180" href="./assets/apple-icon-180x180.png">
  <link href="./assets/favicon.ico" rel="icon">

  <title>Title page</title>  

<link href="./main.d8e0d294.css" rel="stylesheet"></head>

<body class="white">


<!-- Add your site or app content here -->
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6">

        <div class="template-example">
          <h2 class="template-title-example">Text</h2>
          <p>This is bold and this is semi bold and <b>this is extra bold</b>. This is italic and this is extra light and this is light
          and this is regular. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </p>
        </div>

        <div class="template-example">
          <h2 class="template-title-example">Headings</h2>
          
          <table class="table table-bordered">
            <tr><td><h1>H1: Heading 1</h1></td></tr>
            <tr><td><h2>H2: Heading 2</h2></td></tr>
            <tr><td><h3>H3: Heading 3</h3></td></tr>
            <tr><td><h4>H4: Heading 4</h4></td></tr>
          </table>
          
        </div>

        
        <div class="template-example">
          <h2 class="template-title-example">List</h2>
          <div class="row">
            <div class="col-md-6">
              <h3 class="template-title-example">Ordered</h3>
              <ul>
                <li>Consectetur adipiscing elit</li>
                <li>Integer molestie lorem at massa</li>
                <li>Facilisis in pretium nisl aliquet</li>
                <li>Nulla volutpat aliquam velit</li>
              </ul>
            </div>
            <div class="col-md-6">
              <h3 class="template-title-example">Number</h3>
              <ol>
                <li>Consectetur adipiscing elit</li>
                <li>Integer molestie lorem at massa</li>
                <li>Facilisis in pretium nisl aliquet</li>
                <li>Nulla volutpat aliquam velit</li>
              </ol>
            </div>
          </div>
        </div>
        
      </div>

      <div class="col-xs-12 col-md-6">
        <div class="template-example">
          <h2 class="template-title-example">Icons</h2>
          
          <div class="row">
            <div class="col-md-6">
              <h3 class="template-title-example">Social Round</h2>
              <ul class="list-icons">
                <li>
                  <a href="" class="social-round-icon fa-icon">
                    <i class="fa fa-facebook"></i>
                  </a>
                </li>
                <li>
                  <a href="" class="social-round-icon fa-icon">
                    <i class="fa fa-twitter"></i>
                  </a>
                </li>
                <li>
                  <a href="" class="social-round-icon fa-icon">
                    <i class="fa fa-linkedin"></i>
                  </a>
                </li>
                <li>
                  <a href="" class="social-round-icon fa-icon">
                    <i class="fa fa-instagram"></i>
                  </a>
                </li>
              </ul>
            </div>
            <div class="col-md-6">
               <h3 class="template-title-example">Basic Icons</h2>
                <ul class="list-icons">
                  <li>
                    <span class="fa-icon">
                      <i class="fa fa-facebook"></i>
                    </span>
                  </li>
                  <li>
                    <span class="fa-icon">
                      <i class="fa fa-twitter"></i>
                    </span>
                  </li>
                  <li>
                    <span class="fa-icon">
                      <i class="fa fa-linkedin"></i>
                    </span>
                  </li>
                  <li>
                    <span class="fa-icon">
                      <i class="fa fa-instagram"></i>
                    </span>
                  </li>
                </ul>
            </div>

          </div>


          


        </div>

        <div class="template-example">
          <h2 class="template-title-example">Buttons</h2>
          <div class="row">
            <div class="col-md-6">
              <h3 class="template-title-example">Primary</h2>
              <div class="row">
                  <div class="col-md-6">
                  <p><a href="" class="btn btn-primary btn-lg">Primary Large</a></p>
                  <p><a href="" class="btn btn-primary">Primary </a></p>
                  <p><a href="" class="btn btn-primary btn-sm">Primary Small</a></p>
                </div>
              </div>

              <h3 class="template-title-example">Default</h2>
              <div class="row">
                  <div class="col-md-6">
                  <p><a href="" class="btn btn-default btn-lg">Default Large</a></p>
                  <p><a href="" class="btn btn-default">Default </a></p>
                  <p><a href="" class="btn btn-default btn-sm">Default Small</a></p>
                </div>
              </div>

            </div>

            <div class="col-md-6">
              <h3 class="template-title-example">Secondary</h2>
              <div class="row">
                  <div class="col-md-6">
                  <p><a href="" class="btn btn-info btn-lg">Secondary Large</a></p>
                  <p><a href="" class="btn btn-info">Secondary </a></p>
                  <p><a href="" class="btn btn-info btn-sm">Secondary Small</a></p>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        <div class="template-example">
          <h2 class="template-title-example">Inputs</h2>

            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
            </div>

            <div class="form-group">
              <select class="form-control">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </div>

            <div class="form-group">
              <label class="checkbox-inline">
                <input 
                type="checkbox" id="inlineCheckbox1" value="option1"> Email me a copy
              </label>
              <label class="checkbox-inline">
                <input type="checkbox" id="inlineCheckbox2" value="option2"> I am a human
              </label>
            </div>

            <div class="form-group">
              <textarea class="form-control" rows="3" placeholder="Enter your message"></textarea>
            </div>
            
            <div class="alert alert-success" role="alert">Your message was successfully sent</div>
            <div class="alert alert-danger" role="alert">Your message has not been sent, restart</div>
        </div>




      </div>
    </div>
  </div>

<script type="text/javascript" src="./main.bc58148c.js"></script>

templates/edit_profile.html
{% extends 'blog/abstract/base.html' %}
{% block title %}
<title>Edit Profile</title>

{% endblock title %}
{% block body %}
<style>
    .img {
      width:150px;
      height:150px;
      border-radius: 50%;
    }
    .custom-file-input::-webkit-file-upload-button {
        visibility: hidden;
      }
      .custom-file-input::before {
        content: 'Upload Image';
        display: inline-block;
        background: linear-gradient(top, #f9f9f9, #e3e3e3);
        border: 1px solid #999;
        border-radius: 3px;
        padding: 5px 8px;
        outline: none;
        white-space: nowrap;
        -webkit-user-select: none;
        cursor: pointer;
        text-shadow: 1px 1px #fff;
        font-weight: 700;
        font-size: 10pt;
      }
      .custom-file-input:hover::before {
        border-color: black;
      }
      .custom-file-input:active::before {
        background: -webkit-linear-gradient(top, #e3e3e3, #f9f9f9);
      }
</style>
<section id="content-wrap" class="blog-single">
    <div class="row">
        <div class="col-twelve">
            <img class="img" src="{% if request.user.image %}{{request.user.image.url}}{% endif %}">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                  
                  <fieldset>
              
                    <div class="form-field">
                        <label for="sampleRecipientInput">First Name:</label>

                        <input name="fname" type="text" required id="id_title" class="full-width" placeholder="first name" value="{{request.user.first_name}}">
                    </div>
                    <div class="form-field">
                      <label for="sampleRecipientInput">Last Name:</label>

                      <input name="lname" type="text" required id="id_title" class="full-width" placeholder="last name" value="{{request.user.last_name}}">
                  </div>
                  <div class="form-field">
                    <label for="sampleRecipientInput">Email:</label>

                    <input name="email" type="text" required id="id_title" class="full-width" placeholder="Title" value="{{request.user.email}}">
                  </div>
                    <div>
                        <label for="sampleRecipientInput">Gender:</label>
                        <div class="ss-custom-select">
                            <select name="gender" class="full-width" id="sampleRecipientInput">
                                <option value="M">Male</option>
                                <option value="F">Female</option>
                                
                            </select>
                        </div>			         	
                    </div>
                    <div class="message form-field">
                      <label for="sampleRecipientInput">About:</label>

                       <textarea name="about" id="content" class="full-width" placeholder="About Yourself..." value="{{request.user.about}}">{{request.user.about}}</textarea>
                    </div>
                    <div >
                        <label class="required" for="id_image">Image:</label>
                        <p class="file-upload">Currently: 
                          <a href="
                          {% if request.user.image %}{{request.user.image.url}}{% endif %}
                          ">{% if request.user.image %}{{request.user.image.path}}{% endif %}</a><br>

                        <input class="custom-file-input" id="files" type="file" name="image" accept="image/*" >
                    </div>

                    <button type="submit" class="submit button-primary">Submit</button>
              
                  </fieldset>
            </form>
        </div>
    </div>
</section>

{% include "blog/abstract/footer.html" %}

{% endblock body %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  

  <title>Porfolio</title>  

<link href={% static 'main.d8e0d294.css' %} rel="stylesheet"></head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
<title>Bootstrap Example</title>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>






<body class="">
  {% if message %}
    <div class="alert alert-primary" role="alert">
      {{message}}
    </div>
    
  {% endif %}


 

<!-- Add your content of header -->
<div class="background-color-layer" style="background-image: url({% static 'assets/images/img-01.jpg' %})"
></div>
<main class="content-wrapper">
  <header class="white-text-container section-container">
    <div class="text-center">
      <h1>I am {{info.name}}</h1>
      <p>Web developer</p>
      <p>
        <a class="fa-icon fa-icon-2x" href="https://facebook.com/arif.rabbani.902/" title="">
          <i class="fa fa-facebook"></i>
        </a>
       
        <a class="fa-icon fa-icon-2x" href="https://github.com/rabbanibcs" title="">
          <i class="fa fa-github"></i>
        </a>
        <a class="fa-icon fa-icon-2x" href="#" title="">
          <i class="fa fa-linkedin"></i>
        </a>
        
      </p>
    </div>
  </header>



<!-- Add your site or app content here -->
 
 <div class="container">
   <div class="row">
     <div class="col-xs-12">

        <div class="card">
          <div class="card-block">
            <h2>About me</h2>
            <div class="row">
              <div class="col-md-4">
                <p><img src={% static 'assets/images/me.jpg' %} class="img-responsive" alt=""></p>
              </div>
              <div class="col-md-8">

              <p>{{info.about}}</p>

              </div>
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-block">
            <h2>Projects</h2>
            <div class="row">
              <div class="col-md-4">
                <a href="{% url 'post-index' %}"><img src={% static 'assets/images/blog.png' %} class="img-responsive" alt=""></a>
                <h3 class="h5">Blog App (Django)</h3>
                <a href="https://github.com/rabbanibcs/portfolio/tree/main/blog">Source Code</a>
              </div>
              <div class="col-md-4">
                <a href="{% url 'products' %}"><img src={% static "assets/images/shop.png" %} class="img-responsive" alt=""></a>
                <h3 class="h5">Ecommerce App (Django)</h3>
                <a href="https://github.com/rabbanibcs/portfolio/tree/main/ecommerce">Source Code</a>
              </div>
              {% comment %} <div class="col-md-4">
                <img src={% static "assets/images/img-04.jpg"%} class="img-responsive" alt="">
                <h3 class="h5">Denz for Nilon</h3>
                <p>Jan 2017</p>
              </div> {% endcomment %}
            </div>
          </div>
        </div>


        <div class="card">
          <div class="card-block">
            <h2>Education</h2>
            <div class="row">
              <div class="col-md-4">
                <div class="education-experience">
                  <h3 class="h5 date-title">Master of Science</h3>
                  <p>University of Dhaka</p>
                </div>
                
              </div>
              <div class="col-md-4">
                <div class="education-experience">
                  <h3 class="h5 date-title">Bachelor of Science</h3>
                  <p>University of Dhaka</p>
                </div>
              </div>
              
            </div>
          </div>
        </div>
        
        <div class="card">
          <div class="card-block">
            <h2>Language</h2>
            <div class="row">
              <div class="col-md-4">
                <div class="language-experience">
                  <h3 class="h5">English  <small>Fluent</small></h3>
                </div>
              </div>
              <div class="col-md-4">
                <div class="language-experience">
                  <h3 class="h5">Bangla  <small>Fluent</small></h3>
                </div>
              </div>
              
            </div>
          </div>
        </div>

        
        <div class="card">
          <div class="card-block">
            <h2>Social Network</h2>
            <div class="row">
              
              <div class="col-md-3">
                <p class="social-buttons"><a href="https://www.linkedin.com/in/arif-rabbani-325401211/" title=""><span class="social-round-icon fa-icon"><i class="fa fa-linkedin"></i></span>Arif Rabbani</a></p>
              </div>
              <div class="col-md-3">
                <p class="social-buttons"><a href="https://github.com/rabbanibcs" title=""><span class="social-round-icon fa-icon"><i class="fa fa-github"></i></span>Arif Rabbani</a></p>
              </div>
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-block">
            <h2>Contact</h2>
            <form method="POST" class="reveal-content">
              {% csrf_token %}
              <div class="form-group">
                <input name="email" type="email" class="form-control" id="email" placeholder="Email" required>
              </div>
              <div class="form-group">
                <input name="subject" type="text" class="form-control" id="subject" placeholder="Subject" required>
              </div>
              <div class="form-group">
                <textarea name="message" class="form-control" rows="5" placeholder="Enter your message" required></textarea>
              </div>
              <div class="form-group">
                <button type="submit" class=" btn btn-primary">Send message</button>
              </div> 
            </form>
          </div>
        </div>
       
     </div>
   </div>
 </div>

</main>


<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     scrollRevelation('.card');
  });
</script>
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID 

<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
      m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-XXXXX-X', 'auto');
  ga('send', 'pageview');
</script>

--><script type="text/javascript" src={% static "./main.bc58148c.js" %}></script></body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</html>

templates/signin.html
{% extends 'blog/abstract/base.html' %}
{% load static %}
{% block title %}
<title>SignIn</title>

{% endblock title %}
{% block body %}

<section id="content-wrap" class="blog-single">
    <div class="row">
        <div class="col-seven" >
            {% if message %}

            <div class="alert-box ss-notice hideit">
		        <p>{{ message }}</p>
		        <i class="fa fa-times close"></i>
		      </div><!-- /notice -->
                
            {% endif %}

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                  
                  <fieldset>
              
                    <div class="form-field">
                        <label for="sampleRecipientInput">Email:</label>

                        <input name="email" type="text" required id="id_title" class="full-width" placeholder="Email..." value="">
                    </div>

                    <div class="form-field">
                        <label for="sampleRecipientInput">Password:</label>

                        <input type="password" name="password" type="text" required id="id_title" class="full-width" placeholder="Password..." value="">
                    </div>

                    <button type="submit" class="submit button-primary">Sign In</button>
              
                  </fieldset>
            </form>
        <p>Do not have an account? <a href="{% url 'signup' %}"">SignUp now.</a></p>

        </div>
    </div>
</section>
  

{% endblock body %}

templates/signup.html
{% extends 'blog/abstract/base.html' %}
{% load static %}
{% block title %}
<title>SignUp</title>

{% endblock title %}
{% block body %}

<section id="content-wrap" class="blog-single">
    <div class="row">
        <div class="col-seven" >
            {% if message %}

            <div class="alert-box ss-notice hideit">
		        <p>{{ message }}</p>
		        <i class="fa fa-times close"></i>
		      </div><!-- /notice -->
                
            {% endif %}

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                  
                  <fieldset>
              
                    <div class="form-field">
                        <label for="sampleRecipientInput">Email:</label>

                        <input name="email" type="text" required id="id_title" class="full-width" placeholder="Email..." value="">
                    </div>

                    <div class="form-field">
                        <label for="sampleRecipientInput">Password:</label>

                        <input type="password" name="password" type="text" required id="id_title" class="full-width" placeholder="Password..." value="">
                    </div>
                    <div class="form-field">
                        <label for="sampleRecipientInput">Password(again):</label>

                        <input type="password" name="password_" type="text" required id="id_title" class="full-width" placeholder="Password..." value="">
                    </div>

                    <button type="submit" class="submit button-primary">Sign Up</button>
              
                  </fieldset>
            </form>

        </div>
    </div>
</section>
  

{% endblock body %}